# Generated by Django 5.2 on 2025-05-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpense',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financial_manager.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
