# Generated by Django 5.2 on 2025-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_manager', '0003_companydocument_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_tin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='include_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
