# Generated by Django 5.2 on 2025-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_manager', '0007_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signature_choice',
            field=models.CharField(blank=True, choices=[('elisha', 'Elisha Signature'), ('ginye', 'Ginye Signature'), ('siza', 'Siza Signature')], max_length=50, null=True),
        ),
    ]
