# Generated by Django 5.2 on 2025-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_manager', '0008_invoice_signature_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.CharField(max_length=100),
        ),
    ]
